// Generate frozen Unicode classes from the pinned oracle
// Rust compiler's Unicode version.

import { P, Z, Cc } from "uc.micro";
import { writeFile } from "node:fs/promises";

let output = "// Generated by tests/differential/generate-unicode.mjs from uc.micro 3.0.0.\n";
output += "// Unicode data and upstream attribution: see NOTICE.\n\n";
for (const [name, expression] of [
  ["PUNCTUATION", P], ["SEPARATORS", Z], ["CONTROLS", Cc],
]) {
  const re = new RegExp(`^(?:${expression.source})$`);
  const ranges = [];
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (cp >= 0xd800 && cp <= 0xdfff) {
      continue;
    }

    if (!re.test(String.fromCodePoint(cp))) {
      continue;
    }

    if (ranges.length && ranges.at(-1)[1] === cp - 1) {
      ranges.at(-1)[1] = cp;
    } else {
      ranges.push([cp, cp]);
    }
  }

  output += `pub(super) const ${name}: &[(u32, u32)] = &[\n`;
  output += ranges
    .map(([a, b]) => `    (0x${a.toString(16)}, 0x${b.toString(16)}),\n`)
    .join("");
  output += "];\n\n";
}

await writeFile(new URL("../../src/unicode_data.rs", import.meta.url), output);
