class FrontMatter:
    @property
    def kind(self) -> str: ...
    @property
    def raw(self) -> str: ...
    @property
    def start_line(self) -> int: ...
    @property
    def end_line(self) -> int: ...

class MarkdownOutput:
    @property
    def html(self) -> str: ...
    @property
    def frontmatter(self) -> FrontMatter | None: ...

class MarkdownIt:
    def __init__(
        self,
        *,
        html: bool = False,
        linkify: bool = False,
        math: bool = False,
        frontmatter: bool = False,
        typographer: bool = False,
        sourcepos: bool = False,
        heading_anchors: bool = False,
        syntax_highlighting: bool = False,
        syntax_theme: str | None = None,
        syntax_classed: bool = False,
    ) -> None: ...
    def render(self, src: str) -> str: ...
    def parse_frontmatter(self, src: str) -> FrontMatter | None: ...
    def render_with_frontmatter(self, src: str) -> MarkdownOutput: ...
    def syntax_theme_css(self) -> str | None: ...

def available_syntax_themes() -> list[str]: ...
