//! Replaces `"` and `'` quotes with typographic quotation marks.
//!
//! The implementation consumes a lazy text projection of the AST and records
//! byte-based text edits. The tree is mutated only after the complete edit
//! batch has been validated.

use std::collections::HashMap;

use crate::common::utils::is_punct_char;
use crate::parser::core::CoreRule;
use crate::parser::inline::Text;
use crate::parser::inline::builtin::InlineParserRule;
use crate::parser::main::MarkdownIt;
use crate::parser::node::Node;
use crate::parser::text::{
    TextBoundary,
    TextEditBatch,
    TextEvent,
    TextNodeKey,
    TextProjection,
    TextProjectionKind,
};
use crate::plugins::cmark::block::paragraph::Paragraph;
use crate::plugins::cmark::inline::newline::{Hardbreak, Softbreak};
use crate::plugins::html::html_inline::HtmlInline;

const APOSTROPHE: char = '\u{2019}';
const SINGLE_QUOTE: char = '\'';
const DOUBLE_QUOTE: char = '"';
const SPACE: char = ' ';

/// Add smartquotes with the "classic" quote set of `‘`, `’`, `“`, and `”`.
pub fn add(md: &mut MarkdownIt) {
    add_with::<'‘', '’', '“', '”'>(md);
}

pub fn add_with<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>(
    md: &mut MarkdownIt,
) {
    md.add_rule::<SmartQuotesRule<
        OPEN_SINGLE_QUOTE,
        CLOSE_SINGLE_QUOTE,
        OPEN_DOUBLE_QUOTE,
        CLOSE_DOUBLE_QUOTE,
    >>()
    .after::<InlineParserRule>();
}

#[derive(PartialEq, Eq, Debug, Clone, Copy, Hash)]
enum QuoteType {
    Single,
    Double,
}

#[derive(Clone, Copy)]
struct QuoteMarker {
    node: TextNodeKey,
    byte_offset: usize,
    quote_type: QuoteType,
    level: u32,
}

#[derive(Default)]
struct QuoteStack {
    markers: Vec<QuoteMarker>,
    positions: HashMap<(u32, QuoteType), Vec<usize>>,
}

impl QuoteStack {
    fn push(&mut self, marker: QuoteMarker) {
        let position = self.markers.len();
        self.positions
            .entry((marker.level, marker.quote_type))
            .or_default()
            .push(position);
        self.markers.push(marker);
    }

    fn latest(&self, level: u32, quote_type: QuoteType) -> Option<(usize, QuoteMarker)> {
        let position = *self.positions.get(&(level, quote_type))?.last()?;
        Some((position, self.markers[position]))
    }

    fn truncate_for_level(&mut self, level: u32) {
        while self
            .markers
            .last()
            .is_some_and(|marker| marker.level > level)
        {
            self.pop();
        }
    }

    fn truncate(&mut self, len: usize) {
        while self.markers.len() > len {
            self.pop();
        }
    }

    fn pop(&mut self) {
        let marker = self.markers.pop().unwrap();
        let key = (marker.level, marker.quote_type);
        let positions = self.positions.get_mut(&key).unwrap();
        positions.pop();
    }
}

/// smart quotes related events, generated by `TextEvent`
#[derive(Clone, Copy)]
enum RelevantEvent {
    Char {
        node: Option<TextNodeKey>,
        byte_offset: usize,
        ch: char,
        writable: bool,
        nesting_level: u32,
    },
    Space,
}

impl RelevantEvent {
    fn ch(self) -> char {
        match self {
            Self::Char { ch, .. } => ch,
            Self::Space => SPACE,
        }
    }
}

pub struct SmartQuotesRule<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>;

impl<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
> CoreRule
    for SmartQuotesRule<
        OPEN_SINGLE_QUOTE,
        CLOSE_SINGLE_QUOTE,
        OPEN_DOUBLE_QUOTE,
        CLOSE_DOUBLE_QUOTE,
    >
{
    const NAMES: &'static [&'static str] = &["smartquotes"];

    fn run(root: &mut Node, _: &MarkdownIt) {
        let projection = TextProjection::new(smartquotes_projection);
        let mut events = projection.events(root);
        let mut current = next_relevant(&mut events);
        let mut previous = SPACE;
        let mut quote_stack = QuoteStack::default();
        let mut edits = TextEditBatch::new(smartquotes_projection);

        while let Some(event) = current {
            // move to the next pos
            current = next_relevant(&mut events);

            let next_ch = current.map(RelevantEvent::ch).unwrap_or(SPACE);

            let RelevantEvent::Char {
                node,
                byte_offset,
                ch,
                writable,
                nesting_level,
            } = event
            else {
                previous = SPACE;
                continue;
            };

            if writable {
                quote_stack.truncate_for_level(nesting_level);
                let node = node.expect("writable text events always carry a key");
                if ch == SINGLE_QUOTE || ch == DOUBLE_QUOTE {
                    Self::process_quote(
                        node,
                        byte_offset,
                        ch,
                        nesting_level,
                        previous,
                        next_ch,
                        &mut quote_stack,
                        &mut edits,
                    );
                }
            }
            previous = ch;
        }

        edits
            .commit(root)
            .expect("smartquotes creates valid non-overlapping text edits");
    }
}

impl<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
> SmartQuotesRule<OPEN_SINGLE_QUOTE, CLOSE_SINGLE_QUOTE, OPEN_DOUBLE_QUOTE, CLOSE_DOUBLE_QUOTE>
{
    #[allow(clippy::too_many_arguments)]
    fn process_quote(
        node: TextNodeKey,
        byte_offset: usize,
        ch: char,
        level: u32,
        previous: char,
        next: char,
        quote_stack: &mut QuoteStack,
        edits: &mut TextEditBatch,
    ) {
        let quote_type = if ch == SINGLE_QUOTE {
            QuoteType::Single
        } else {
            QuoteType::Double
        };
        let (can_open, can_close) = can_open_or_close(quote_type, previous, next);

        if !can_open && !can_close {
            if quote_type == QuoteType::Single {
                edits.replace_char(node, byte_offset..byte_offset + 1, APOSTROPHE);
            }
            return;
        }

        if can_close {
            if let Some((position, opener)) = quote_stack.latest(level, quote_type) {
                let (open_quote, close_quote) = match quote_type {
                    QuoteType::Single => (OPEN_SINGLE_QUOTE, CLOSE_SINGLE_QUOTE),
                    QuoteType::Double => (OPEN_DOUBLE_QUOTE, CLOSE_DOUBLE_QUOTE),
                };
                edits.replace_char(
                    opener.node,
                    opener.byte_offset..opener.byte_offset + 1,
                    open_quote,
                );
                edits.replace_char(node, byte_offset..byte_offset + 1, close_quote);
                quote_stack.truncate(position);
                return;
            }
        }

        if can_open {
            quote_stack.push(QuoteMarker {
                node,
                byte_offset,
                quote_type,
                level,
            });
        } else if can_close && quote_type == QuoteType::Single {
            edits.replace_char(node, byte_offset..byte_offset + 1, APOSTROPHE);
        }
    }
}

/// next releted event
fn next_relevant(events: &mut impl Iterator<Item = TextEvent>) -> Option<RelevantEvent> {
    loop {
        match events.next()? {
            TextEvent::Char {
                node,
                byte_offset,
                ch,
                writable,
                nesting_level,
            } => {
                return Some(RelevantEvent::Char {
                    node,
                    byte_offset,
                    ch,
                    writable,
                    nesting_level,
                });
            }
            TextEvent::Boundary(TextBoundary::Space) => return Some(RelevantEvent::Space),
            TextEvent::Enter { nesting_level } | TextEvent::Exit { nesting_level } => {
                let _ = nesting_level;
            }
        }
    }
}

/// classify
fn smartquotes_projection(node: &Node) -> TextProjectionKind<'_> {
    if let Some(text) = node.cast::<Text>() {
        // normal text, editable
        TextProjectionKind::Writable(text)
    } else if let Some(html) = node.cast::<HtmlInline>() {
        // HTML, not editable (protect quotes for <a href="...">)
        TextProjectionKind::ReadOnly(&html.content)
    } else if node.is::<Paragraph>() || node.is::<Hardbreak>() || node.is::<Softbreak>() {
        // boundary, process stack content
        TextProjectionKind::Boundary(TextBoundary::Space)
    } else {
        // other rule, do nothing
        TextProjectionKind::Transparent
    }
}

fn can_open_or_close(quote_type: QuoteType, last_char: char, next_char: char) -> (bool, bool) {
    let is_double = quote_type == QuoteType::Double;
    if next_char == DOUBLE_QUOTE && is_double && last_char.is_ascii_digit() {
        return (false, false);
    }

    let is_last_punctuation = last_char.is_ascii_punctuation() || is_punct_char(last_char);
    let is_next_punctuation = next_char.is_ascii_punctuation() || is_punct_char(next_char);
    let is_last_whitespace = last_char.is_whitespace();
    let is_next_whitespace = next_char.is_whitespace();

    let can_open =
        !is_next_whitespace && (!is_next_punctuation || is_last_whitespace || is_last_punctuation);
    let can_close =
        !is_last_whitespace && (!is_last_punctuation || is_next_whitespace || is_next_punctuation);

    if can_open && can_close {
        return (is_last_punctuation, is_next_punctuation);
    }
    (can_open, can_close)
}

#[cfg(test)]
mod tests {
    #[test]
    fn smartquotes_basics() {
        let md = &mut crate::MarkdownIt::empty();
        crate::plugins::cmark::add(md);
        crate::plugins::extra::smartquotes::add(md);
        let html = md.parse(r#"'hello' "world""#).render();
        assert_eq!(html.trim(), r#"<p>‘hello’ “world”</p>"#);
    }

    #[test]
    fn smartquotes_shouldnt_affect_html() {
        let md = &mut crate::MarkdownIt::empty();
        crate::plugins::cmark::add(md);
        crate::plugins::html::html_inline::add(md);
        crate::plugins::extra::smartquotes::add(md);
        let html = md.parse(r#"<a href="hello"></a>"#).render();
        assert_eq!(html.trim(), r#"<p><a href="hello"></a></p>"#);
    }

    #[test]
    fn smartquotes_should_work_with_typographer() {
        let md = &mut crate::MarkdownIt::empty();
        crate::plugins::cmark::add(md);
        crate::plugins::html::html_inline::add(md);
        crate::plugins::extra::typographer::add(md);
        crate::plugins::extra::smartquotes::add(md);
        let html = md.parse("\"**...**\"").render();
        assert_eq!(html.trim(), "<p>“<strong>…</strong>”</p>");
    }

    #[test]
    fn unicode_before_quotes_uses_byte_offsets() {
        let md = &mut crate::MarkdownIt::empty();
        crate::plugins::cmark::add(md);
        crate::plugins::extra::smartquotes::add(md);
        assert_eq!(md.parse("雪 \"雨\"").render(), "<p>雪 “雨”</p>\n");
    }
}
