//! Replaces `"` and `'` quotes with typographic quotation marks.
//!
//! The implementation consumes a lazy text projection of the AST and records
//! byte-based text edits. The tree is mutated only after the complete edit
//! batch has been validated.

use std::collections::HashMap;

use crate::common::utils::is_punct_char;
use crate::document::Text;
use crate::plugins::cmark::block::paragraph::Paragraph;
use crate::plugins::cmark::inline::newline::{Hardbreak, Softbreak};
use crate::plugins::html::html_inline::HtmlInline;
use crate::{
    Document,
    DocumentTransform,
    EditBatch,
    MarkdownIt,
    NodeId,
    NodeRef,
    TextBoundary,
    TextEvent,
    TextProjection,
    TextProjectionKind,
};

const APOSTROPHE: char = '\u{2019}';
const SINGLE_QUOTE: char = '\'';
const DOUBLE_QUOTE: char = '"';
const SPACE: char = ' ';

/// Add smartquotes with the "classic" quote set of `‘`, `’`, `“`, and `”`.
pub fn add(md: &mut MarkdownIt) {
    add_with::<'‘', '’', '“', '”'>(md);
}

/// Register smartquotes with a custom compile-time quote set.
pub fn add_with<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>(
    md: &mut MarkdownIt,
) {
    md.add_document_transform::<SmartQuotesDocumentTransform<
        OPEN_SINGLE_QUOTE,
        CLOSE_SINGLE_QUOTE,
        OPEN_DOUBLE_QUOTE,
        CLOSE_DOUBLE_QUOTE,
    >>();
}

/// The classic smartquotes transform used by [`add`].
pub type ClassicSmartQuotesDocumentTransform = SmartQuotesDocumentTransform<'‘', '’', '“', '”'>;

/// Arena-backed smartquotes with a compile-time quote set.
#[derive(Default)]
pub struct SmartQuotesDocumentTransform<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>;

impl<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
> DocumentTransform
    for SmartQuotesDocumentTransform<
        OPEN_SINGLE_QUOTE,
        CLOSE_SINGLE_QUOTE,
        OPEN_DOUBLE_QUOTE,
        CLOSE_DOUBLE_QUOTE,
    >
{
    const KEY: &'static str = "extra::smartquotes";
    const ALIASES: &'static [&'static str] = &["smartquotes"];

    fn run(&self, document: &Document) -> EditBatch {
        document_edits_with::<
            OPEN_SINGLE_QUOTE,
            CLOSE_SINGLE_QUOTE,
            OPEN_DOUBLE_QUOTE,
            CLOSE_DOUBLE_QUOTE,
        >(document)
    }
}

fn document_edits_with<
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>(
    document: &Document,
) -> EditBatch {
    let mut edits = EditBatch::new();
    let projection = TextProjection::new(document_smartquotes_projection);
    let events = document
        .text_events(projection)
        .filter_map(document_relevant_event);
    transform_events::<
        NodeId,
        _,
        _,
        OPEN_SINGLE_QUOTE,
        CLOSE_SINGLE_QUOTE,
        OPEN_DOUBLE_QUOTE,
        CLOSE_DOUBLE_QUOTE,
    >(events, |node, byte_offset, replacement| {
        edits.replace_char(node, byte_offset..byte_offset + 1, replacement);
    });
    edits
}

#[derive(PartialEq, Eq, Debug, Clone, Copy, Hash)]
enum QuoteType {
    Single,
    Double,
}

#[derive(Clone, Copy)]
struct QuoteMarker<K> {
    node: K,
    byte_offset: usize,
    quote_type: QuoteType,
    level: u32,
}

struct QuoteStack<K> {
    markers: Vec<QuoteMarker<K>>,
    positions: HashMap<(u32, QuoteType), Vec<usize>>,
}

impl<K> Default for QuoteStack<K> {
    fn default() -> Self {
        Self {
            markers: Vec::new(),
            positions: HashMap::new(),
        }
    }
}

impl<K: Copy> QuoteStack<K> {
    fn push(&mut self, marker: QuoteMarker<K>) {
        let position = self.markers.len();
        self.positions
            .entry((marker.level, marker.quote_type))
            .or_default()
            .push(position);
        self.markers.push(marker);
    }

    fn latest(&self, level: u32, quote_type: QuoteType) -> Option<(usize, QuoteMarker<K>)> {
        let position = *self.positions.get(&(level, quote_type))?.last()?;
        Some((position, self.markers[position]))
    }

    fn truncate_for_level(&mut self, level: u32) {
        while self
            .markers
            .last()
            .is_some_and(|marker| marker.level > level)
        {
            self.pop();
        }
    }

    fn truncate(&mut self, len: usize) {
        while self.markers.len() > len {
            self.pop();
        }
    }

    fn pop(&mut self) {
        let marker = self.markers.pop().unwrap();
        let key = (marker.level, marker.quote_type);
        let positions = self.positions.get_mut(&key).unwrap();
        positions.pop();
    }
}

/// smart quotes related events, generated by `TextEvent`
#[derive(Clone, Copy)]
enum RelevantEvent<K> {
    Char {
        node: Option<K>,
        byte_offset: usize,
        ch: char,
        writable: bool,
        nesting_level: u32,
    },
    Space,
    HardBoundary,
}

impl<K> RelevantEvent<K> {
    fn ch(self) -> char {
        match self {
            Self::Char { ch, .. } => ch,
            Self::Space | Self::HardBoundary => SPACE,
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn process_quote<
    K: Copy,
    F: FnMut(K, usize, char),
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>(
    node: K,
    byte_offset: usize,
    ch: char,
    level: u32,
    previous: char,
    next: char,
    quote_stack: &mut QuoteStack<K>,
    replace: &mut F,
) {
    let quote_type = if ch == SINGLE_QUOTE {
        QuoteType::Single
    } else {
        QuoteType::Double
    };
    let (can_open, can_close) = can_open_or_close(quote_type, previous, next);

    if !can_open && !can_close {
        if quote_type == QuoteType::Single {
            replace(node, byte_offset, APOSTROPHE);
        }
        return;
    }

    if can_close {
        if let Some((position, opener)) = quote_stack.latest(level, quote_type) {
            let (open_quote, close_quote) = match quote_type {
                QuoteType::Single => (OPEN_SINGLE_QUOTE, CLOSE_SINGLE_QUOTE),
                QuoteType::Double => (OPEN_DOUBLE_QUOTE, CLOSE_DOUBLE_QUOTE),
            };
            replace(opener.node, opener.byte_offset, open_quote);
            replace(node, byte_offset, close_quote);
            quote_stack.truncate(position);
            return;
        }
    }

    if can_open {
        quote_stack.push(QuoteMarker {
            node,
            byte_offset,
            quote_type,
            level,
        });
    } else if can_close && quote_type == QuoteType::Single {
        replace(node, byte_offset, APOSTROPHE);
    }
}

fn transform_events<
    K: Copy,
    I: Iterator<Item = RelevantEvent<K>>,
    F: FnMut(K, usize, char),
    const OPEN_SINGLE_QUOTE: char,
    const CLOSE_SINGLE_QUOTE: char,
    const OPEN_DOUBLE_QUOTE: char,
    const CLOSE_DOUBLE_QUOTE: char,
>(
    mut events: I,
    mut replace: F,
) {
    let mut current = events.next();
    let mut previous = SPACE;
    let mut quote_stack = QuoteStack::default();

    while let Some(event) = current {
        current = events.next();
        let next_ch = current.map(RelevantEvent::ch).unwrap_or(SPACE);

        let RelevantEvent::Char {
            node,
            byte_offset,
            ch,
            writable,
            nesting_level,
        } = event
        else {
            previous = SPACE;
            if matches!(event, RelevantEvent::HardBoundary) {
                quote_stack.truncate(0);
            }
            continue;
        };

        if writable {
            quote_stack.truncate_for_level(nesting_level);
            let node = node.expect("writable text events always carry a node ID");
            if ch == SINGLE_QUOTE || ch == DOUBLE_QUOTE {
                process_quote::<
                    K,
                    F,
                    OPEN_SINGLE_QUOTE,
                    CLOSE_SINGLE_QUOTE,
                    OPEN_DOUBLE_QUOTE,
                    CLOSE_DOUBLE_QUOTE,
                >(
                    node,
                    byte_offset,
                    ch,
                    nesting_level,
                    previous,
                    next_ch,
                    &mut quote_stack,
                    &mut replace,
                );
            }
        }
        previous = ch;
    }
}

fn document_relevant_event(event: TextEvent) -> Option<RelevantEvent<NodeId>> {
    match event {
        TextEvent::Char {
            node,
            byte_offset,
            ch,
            writable,
            nesting_level,
        } => Some(RelevantEvent::Char {
            node: Some(node),
            byte_offset,
            ch,
            writable,
            nesting_level,
        }),
        TextEvent::Boundary(TextBoundary::Space) => Some(RelevantEvent::Space),
        TextEvent::Boundary(TextBoundary::Hard) => Some(RelevantEvent::HardBoundary),
        TextEvent::Enter { .. } | TextEvent::Exit { .. } => None,
    }
}

fn document_smartquotes_projection(node: NodeRef<'_>) -> TextProjectionKind<'_> {
    if let Some(text) = node.cast::<Text>() {
        // normal text, editable
        TextProjectionKind::Writable(&text.content)
    } else if let Some(html) = node.cast::<HtmlInline>() {
        // HTML, not editable (protect quotes for <a href="...">)
        TextProjectionKind::ReadOnly(&html.content)
    } else if node.is::<Paragraph>() || node.is::<Hardbreak>() || node.is::<Softbreak>() {
        // boundary, process stack content
        TextProjectionKind::Boundary(TextBoundary::Space)
    } else {
        // other rule, do nothing
        TextProjectionKind::Transparent
    }
}

fn can_open_or_close(quote_type: QuoteType, last_char: char, next_char: char) -> (bool, bool) {
    let is_double = quote_type == QuoteType::Double;
    if next_char == DOUBLE_QUOTE && is_double && last_char.is_ascii_digit() {
        return (false, false);
    }

    let is_last_punctuation = last_char.is_ascii_punctuation() || is_punct_char(last_char);
    let is_next_punctuation = next_char.is_ascii_punctuation() || is_punct_char(next_char);
    let is_last_whitespace = last_char.is_whitespace();
    let is_next_whitespace = next_char.is_whitespace();

    let can_open =
        !is_next_whitespace && (!is_next_punctuation || is_last_whitespace || is_last_punctuation);
    let can_close =
        !is_last_whitespace && (!is_last_punctuation || is_next_whitespace || is_next_punctuation);

    if can_open && can_close {
        return (is_last_punctuation, is_next_punctuation);
    }
    (can_open, can_close)
}
