name: tests

on:
  - push
  - pull_request

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v6
      - run: cargo test
